############################
## Author
############################

author:
  name: "Yoela O."
  image: author.JPEG
  greeting: "My LinkTree :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/BravishkaSkytano
  # - link: https://github.com/Chrede88/L1nkr#readme
  - website: https://bravishkaskytano.github.io/blog
  # - x-twitter:
  # - mastodon:
  - linkedin: https://www.linkedin.com/in/yoela-o/
  # - instagram:
  - reddit: https://www.reddit.com/user/Y_Mystake_O/
  - telegram: https://t.me/BravishkaSkytano
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - email:
  - discord: https://discord.com/users/7h33013751036641441
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 3

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: true

###############################
## OpenGraph & Twitter Cards
###############################

title: "Yoela O."
description: "My LinkTree built with L1nkr & Hugo"
images:
  - thumbnail.png
